### ISSUE TITLE
Firefox Autoconfig

### ISSUE THREAD

**Issue by jfuchtm** [autopkg/patgmac-recipes#3]
Pat, about 4 years ago you created a Firefox file, FirefoxAutoconfig.lanrev.recipe. I know you are using some Filewave and I was wondering if you can make the same. I can't seem to figure out how to make this thing work to publish my own so I am asking kindly.

Thanks

Jeff

**Comment by patgmac** [comment]
Sorry, I haven't gotten into making FW recipes yet and I no longer have a need for autoconfig. I didn't think this was even a thing anymore.

**Comment by jfuchtm** [comment]
Our CK web filter requires the cert placed in the browser, easy to do on all but Mac Firefox. GPO for Windows Firefox but placement on Mac is impossible.
